### ISSUE TITLE
Question about max frequency

### ISSUE THREAD

**Issue by vladbalmos** [richardjkendall/rp2040-freq-counter#3]
Hi,

I'm interested in doing something similar, more exactly to create a frequency counter for an AM/FM radio display. What is the maximum frequency that can be measurable using the PIO implementation?

Thanks!

**Comment by richardjkendall** [comment]
Hi @vladbalmos 

The PIO state machines can execute one instruction every clock cycle.  The standard clock speed on an RP2040 is 125MHz - so one instruction every 8ns, although you can (and I did) increase the clock speed, so in my implementation it runs at 250MHz or one instruction every 4ns.

In my frequency counter PIO, it takes 6 instructions to fully run through, so the theoretical max would be those 6 instructions being executed in a constant cycle, which would be 250MHz/6 = 41.6MHz.

Noting I've not tested this, and I think other architectures like a reciprocal counter would suit your need better.
